# Project Information
site_name: TechTutorials
site_description: This website is a place to share what i have learned from working with latest computer technologies
site_author: Sanket Lawangare
site_url: https://pages.github.com/sanket4373/tech-essential-docs

#Repository Information
repo_name: sanket4373/tech-essential-docs
repo_url: https://github.com/sanket4373/tech-essential-docs
remote_name: origin
edit_uri: edit/master/docs/

# Page tree
nav:
  - Home:
    - index.md
    - home/contributing.md
  - Docker:
    - docker/install_run_docker.md
  - Networking:
    - networking/basic_concepts.md
    - networking/commands_cheatsheet.md  
    - networking/DNS.md  

# Configuration
theme:
  name: material
  custom_dir: theme
  logo:
    icon: cloud
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  feature:
    tabs: true
  palette:
    primary: default
    accent: default

# Customization
extra_css:
  - assets/styles/extra.css

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs/_snippets
  - pymdownx.superfences:
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
